name: pr-agent

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest

    steps:
      - name: PR-Agent
        uses: qodo-ai/pr-agent@main

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # ==================================================
          # GROQ
          # ==================================================
          GROQ.KEY: ${{ secrets.GROQ_API_KEY }}

          # ==================================================
          # PR-AGENT
          # ==================================================
          config.model: "groq/openai/gpt-oss-120b"
          config.fallback_models: '["groq/openai/gpt-oss-120b"]'

          github_action_config.auto_describe: "true"
          github_action_config.auto_review: "false"
          github_action_config.auto_improve: "false"